# Generated by Django 4.2.10 on 2024-03-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('finished_time', models.DateTimeField(blank=True, null=True)),
                ('aborted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField(default=3, verbose_name='Field size')),
                ('min_length', models.IntegerField(default=3, verbose_name='Line length')),
                ('allow_horizontal', models.BooleanField(default=True)),
                ('allow_vertical', models.BooleanField(default=True)),
                ('allow_diagonal', models.BooleanField(default=True)),
                ('finish_line', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'verbose_name': 'Move',
                'verbose_name_plural': 'Moves',
                'ordering': ('created',),
            },
        ),
    ]
